language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.7"
sudo: false
install:
  - pip install python-coveralls
  - pip install coveralls
  - pip install cachetools
script: nosetests tests --verbose --with-coverage
after_success:
  - coveralls
notifications:
  email: false
